name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Delete old backend docker container
        run: sudo docker rm -f cicd-pipeline-backend-container || true
      - name: Delete old frontend docker container
        run: sudo docker rm -f cicd-pipeline-frontend-container || true
      - name: Delete all docker image
        run: sudo docker rmi -f $(docker images -aq) || true

      - name: Pull backend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-backend:latest
      - name: Run backend docker container
        run: sudo docker run -d --network mynetwork -p 9000:9000 --name cicd-pipeline-backend-container gyarmatiadam/cicd-pipeline-backend

      - name: Pull frontend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-frontend:latest
      - name: Run frontend docker container
        run: sudo docker run -d --network mynetwork -p 80:80 --name cicd-pipeline-frontend-container gyarmatiadam/cicd-pipeline-frontend
