name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull backend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-backend:latest
      - name: Delete old docker container
        run: sudo docker rm -f cicd-pipeline-backend-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-backend-container gyarmatiadam/cicd-pipeline-backend

      - name: Pull frontend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-frontend:latest
      - name: Delete old docker container
        run: sudo docker rm -f cicd-pipeline-frontend-container || true
      - name: Run docker container
        run: sudo docker run -d --network=host --name cicd-pipeline-frontend-container gyarmatiadam/cicd-pipeline-frontend
