name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Backend Docker image
      run: docker build -t gyarmatiadam/cicd-pipeline-backend security-demo-with-angular/
    - name: Backend image push to Dockerhub
      run: docker push gyarmatiadam/cicd-pipeline-backend:latest

    - name: Build the Frontend Docker image
      run: docker build -t gyarmatiadam/cicd-pipeline-frontend angular-security-jwt/
    - name: Frontend image push to Dockerhub
      run: docker push gyarmatiadam/cicd-pipeline-frontend:latest



